version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_AUTH_PROVIDER_DOMAIN=dyersituations.us.auth0.com
      - REACT_APP_AUTH_PROVIDER_CLIENT_ID=olQbSDoYvniA5XQ663HGBGOCT1erGOW4
      - REACT_APP_AUTH_PROVIDER_AUDIENCE=hasura
      - REACT_APP_GRAPHQL_URI=http://localhost:8080/v1/graphql