version: "3.7"
services:
  cypress:
    image: cypress/included:6.2.0
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
      - ./node_modules:/e2e/node_modules
    network_mode: host
    depends_on:
      - app
